version: '3.7'
services:
  notification-etl-service:
    # Service to run the notification service for ETL process with decaf and stellar blockchain
    image: notification-etl-service:latest
    env_file:
      - docker.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        # Environment variables for the notification ETL service
        SERVER_PORT_LISTENING: ${SERVER_PORT_LISTENING}
        NODE_ENV: ${NODE_ENV}
        CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
        HOST_DB_CONFIG: ${HOST_DB_CONFIG}
        PORT_DB_CONFIG: ${PORT_DB_CONFIG}
        DIALECT_DB_CONFIG: ${DIALECT_DB_CONFIG}
        PROTOCOL_DB_CONFIG: ${PROTOCOL_DB_CONFIG}
        DATABASE_NAME_DB_CONFIG: ${DATABASE_NAME_DB_CONFIG}
        LOG_DEBUG_DB_CONFIG: ${LOG_DEBUG_DB_CONFIG}
        USER_NAME_DB_CONFIG: ${USER_NAME_DB_CONFIG}
        USER_PASSWORD_DB_CONFIG: ${USER_PASSWORD_DB_CONFIG}
    restart: always
    ports:
      - '3090:3090' # Port to access the notification service API
    volumes:
      - ./notification-etl-service-data:/notification-etl-service
    depends_on:
      # Declare dependencies for startup
      - postgres
      - rabbitmq
    networks:
      - notification-api-network
  rabbitmq:
    # Service to run RabbitMQ and handle the message queue for notification service
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=notification_service_api_mq
      - RABBITMQ_DEFAULT_PASS=notification_service_api_mq
    ports:
      - "5672:5672" # RabbitMQ for AMQP protocol
      - "15672:15672" #RabbitMQ Management UI
      - "15692:15692" #Prometheus Exporter
    networks:
      - notification-api-network
  # Service to run the mock server for testing the notification service with decaf API
  decaf-api-mockserver:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/spec.json
      # Hot reload when the spec.json changes (useful for development)
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      # bind the config for easy editing
      - ./config-mock-server:/config
    networks:
      - notification-api-network
  prometheus:
    # Service to run Prometheus for monitoring the notification service
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Prometheus UI
    networks:
      - notification-api-network
  grafana:
    # Service to run Grafana for monitoring the notification service
    image: grafana/grafana-enterprise
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    restart: unless-stopped
    volumes:
      # Grafana data storage
      - ./grafana-storage:/var/lib/grafana
      # Grafana configuration for dashboard import
      # - ./dashboard-monitoring-grafana:/etc/grafana/provisioning
    ports:
      - "3000:3000"  # Grafana UI
    networks:
      - notification-api-network
  postgres:
    # Service to run the PostgresSQL database for the notification service
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification-service
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - notification-api-network
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/notification-service?sslmode=disable"
    links:
      - postgres
      - prometheus
    depends_on:
      # Declare dependencies for startup
      - postgres
    networks:
      - notification-api-network
networks:
  notification-api-network:
