global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Job to scrape rabbitmq metrics
  - job_name: "rabbitmq"
    static_configs:
      - targets: [ "rabbitmq:15692" ]
  # Job to scrape postgres metrics
  - job_name: "postgres"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
