{
 "title": "Notification service overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Client user notifications to push",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of consumer to push notifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rabbitmq_queue_consumers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total accounts imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM account LIMIT 50 "
    }
   ]
  },
  {
   "title": "Imported users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM subscription LIMIT 50 "
    }
   ]
  },
  {
   "title": "Imported user details",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \"userId\", username, email, \"subscriptionId\", \"createdAt\" FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Subscription details",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT name, id, \"createdAt\" FROM subscription LIMIT 50 "
    }
   ]
  },
  {
   "title": "Accounts imported",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \"publicKey\", chain, \"userId\", \"isActivated\", \"isPrivate\", \"createdAt\" FROM account LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last users from Decaf API",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "json_options": {
      "root_is_not_array": false
     },
     "source": "url",
     "type": "json",
     "url": "https://68b4d0f0-d56c-476b-9b2b-367806e0abad.mock.pstmn.io/searchUserProfile",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}